name: Auto-Assign and Move Issue

on:
  issues:
    types:
      - opened
  push:
    branches:
      - Issue1

jobs:
  assign-and-move:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Issue Creator
        run: |
          ISSUE_NUMBER=$(jq -r '.issue.number' $GITHUB_EVENT_PATH)
          ISSUE_CREATOR=$(jq -r '.issue.user.login' $GITHUB_EVENT_PATH)
          
          # Assign the issue creator as an assignee
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"assignees\":[\"$ISSUE_CREATOR\"]}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/assignees"

      - name: Add Issue to 'DUMMY PROJECT' Project
        run: |
          PROJECT_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/projects" | jq '.[] | select(.name == "DUMMY PROJECT").id')
          COLUMN_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/projects/$PROJECT_ID/columns" | jq '.[0].id')
          ISSUE_NUMBER=$(jq -r '.issue.number' $GITHUB_EVENT_PATH)
          
          # Add the issue to the 'DUMMY PROJECT' project
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"content_id\":$ISSUE_NUMBER,\"content_type\":\"Issue\"}" \
            "https://api.github.com/projects/columns/$COLUMN_ID/cards"

      - name: Move Issue to 'In Progress' Column
        run: |
          PROJECT_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/projects" | jq '.[] | select(.name == "KANBAN").id')
          COLUMN_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/projects/$PROJECT_ID/columns" | jq '.[] | select(.name == "In Progress").id')
          ISSUE_NUMBER=$(jq -r '.issue.number' $GITHUB_EVENT_PATH)
          
          # Move the issue to the 'In Progress' column
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"content_id\":$ISSUE_NUMBER,\"content_type\":\"Issue\"}" \
            "https://api.github.com/projects/columns/$COLUMN_ID/cards"
